config/routes.rb
Rails.application.routes.draw do
  resources :absences
  resources :grades
  resources :activities
  resources :lessons
  resources :disciplines
  devise_for :users
  resources :courses
  resources :schools
  resources :discanexo

  post 'disciplines/:id' => 'disciplines#deleteAnexo'
  get 'update_users' => "grades#update_users", as: :update_users, defaults: { format: 'js' }

  get 'calendario' => 'activities#indexCalendar', as: :calendar
  
  get 'disciplines/:id/matricula' => 'disciplines#matricula', as: :matricula
  root 'activities#indexRoot'

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :Course
  has_many :Activity, :dependent => :destroy
  has_many :Discuser, :dependent => :destroy
  has_many :Users, through: :Discuser
  belongs_to :Users
  has_many :discanexo, :dependent => :destroy

  validates_presence_of :nome, :cargahoraria

  def nomecompleto
  	"#{codigo} - #{nome}"
  end

end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  before_action :set_discipline_matricula, only: [:matricula]
  before_action :authenticate_user!


  # GET /disciplines
  # GET /disciplines.json
  def index
    if( current_user.admin? )
      @disciplines = Discipline.where( users_id: current_user.id)
      @discipline = Discipline.new
    else
      @disciplines = Discipline.joins(:Discuser).where("user_id = (?)", current_user.id)
      @discipline = Discipline.new
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  #
  def matricula
    disc = @discipline
    user = current_user

    Discuser.create( User: user, Discipline: disc)

    respond_to do |format|
      format.html { redirect_to @discipline, notice: 'Matricula realizada com sucesso.' }
    end

  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)
    @discipline.users_id = current_user.id

    respond_to do |format|
      if @discipline.save
        @discipline.codigo = "DISC-%04d" % [@discipline.id]
        @discipline.save
        if params[:anexos]

          params[:anexos].each { |anx|
            @discanexo = Discanexo.new
            @discanexo.anexo = anx
            @discanexo.Discipline_id = @discipline.id
            @discanexo.save
          }
        end
        flash[:success] = "Disciplina cadastrada com sucesso."
        format.html { redirect_to @discipline}
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      @senha = @discipline.senha
      if @discipline.update(discipline_params)
        if @discipline.senha == ""
          @discipline.senha = @senha
          @discipline.update( senha: @senha)
        end
        if params[:anexos]

          params[:anexos].each { |anx|
            @discanexo = Discanexo.new
            @discanexo.anexo = anx
            @discanexo.Discipline_id = @discipline.id
            @discanexo.save
          }
        end
        flash[:success] = "Disciplina atualizada com sucesso."
        format.html { redirect_to disciplines_url}
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  def deleteAnexo
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: params[:toba].to_s}
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discanexos = Discanexo.where("id in (?)", @discipline.discanexo_ids)
    if @discanexos
      @discanexos.each { |anx|
        anx.anexo = nil
        anx.save
      }
    end
    @discipline.save
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    def set_discipline_matricula
      @discipline = Discipline.find(params[:disciplineMat])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:nome, :cargahoraria, :Course_id, :users_id, :anexos, :disciplineMat, :senha)
    end

  end

app/helpers/disciplines_helper.rb
module DisciplinesHelper

end

app/views/disciplines/_edit.html.erb
<%= form_for(discipline, html: { multipart: true })  do |f| %>
  <% if discipline.errors.any? %>
    <div >
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, required: true%>
  </div>
  <div class="field">
    <%= f.label :cargahoraria %><br>
    <%= f.number_field :cargahoraria, required: true , min: 0 %>
  </div>
  <div class="field">
    <%= f.label "Nova Senha" %><br>
    <%= f.password_field :senha%>
  </div>
  <div class="field">
    <%= f.label :Anexos %>
    <%= file_field_tag "anexos[]", type: :file, multiple: true%>
  </div>

  <div class="modal-footer">
  <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
  <%= f.submit 'Save Changes', :class => 'btn btn-primary'  %>
  </div>
<% end %>

app/views/disciplines/_form.html.erb
<%= form_for(@discipline, html: { multipart: true })  do |f| %>
  <% if @discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discipline.errors.count, "error") %> prohibited this @discipline from being saved:</h2>

      <ul>
      <% @discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, required: true%>
  </div>
  <div class="field">
    <%= f.label :cargahoraria %><br>
    <%= f.number_field :cargahoraria, required: true , min: 0 %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.password_field :senha %>
  </div>
  <div class="field">
    <%= f.label :Anexos %>
    <%= file_field_tag "anexos[]", type: :file, multiple: true%>
  </div>
  <div class="modal-footer">
  <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
  <%= f.submit 'Save Changes', :class => 'btn btn-primary'  %>
  </div>
<% end %>

app/views/disciplines/_matricula.html.erb
<%= form_tag(matricula_path(:disciplineMat), method: 'get') do %>
<% @discAbertas = Discipline.where("id not in (?)",
	Discipline.select(:id)
	.joins(:Discuser)
	.where("user_id = (?)", current_user.id))
	%>
	<%= label_tag 'Escolha uma disciplina para matricular-se:' %> <br>
	<%= select_tag 'disciplineMat', options_from_collection_for_select(@discAbertas, :id, :nomecompleto), {required: true, class: "form-control"} %>

	<div class="modal-footer">
		<%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
		<%= submit_tag "Matricular", name: nil, class: 'btn btn-primary btn-sm' %>
	</div>
	<% end %> 

app/views/disciplines/_show.html.erb
<p>
  <strong>Nome:</strong>
  <%= discipline.nome %>
</p>

<p>
  <strong>Cargahoraria:</strong>
  <%= discipline.cargahoraria %>
</p>

<p>
  <strong>Anexo:</strong>
  <%= link_to "Download", @discipline.anexo.url(:original, false) %> 
</p>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/_showDetails.html.erb
<div class="table">
    <div class="row">
       <div class="cell twocol">
           <span>Atividade</span>
       </div>
       <div class="cell twocol">
           <span>Nota</span>
       </div>
    <% @soma = 0.0 %>
    <% discipline.Activity.each do |atv| %>
    <div class="row">
       <div class="cell twocol">
           <span><%= atv.nome %></span>
       </div>
       <% obj = atv.Grade.find_by( User_id: current_user.id ) %>
       <% nota = obj ? obj.nota : 0.0 %>
       <div class="cell twocol">
           <span><%= nota %></span>
       </div>
       <% @soma += nota.to_i%>
       <% end %>
       <div class="cell twocol">
           <span>Total:</span>
       </div>
        <div class="cell twocol">
           <span><%= @soma %></span>
       </div>
    
</div>

app/views/disciplines/_showMateriais.html.erb
   <% if current_user.admin? 
      @class = "cell thrcol"
   else
      @class = "cell twocol"
   end%>

<% @materiais = discipline.discanexo %>
<div class="table">
  <div class="row">
   <div class="<%= @class %>">
     <span>Arquivo</span>
   </div>
   <div class="<%= @class %>">
     <span>Link</span>
   </div> 
   <% if current_user.admin? %>
   <div class="<%= @class %>">
     <span>Apagar</span>
   </div> 
   <% end %>
   
   <% @materiais.each do |mat| %>
   <div class="row">
     <div class="<%= @class %>">
       <span><%= mat.anexo.original_filename%></span>
     </div>
     <div class="<%= @class %>">
       <span><%= link_to "Anexo", mat.anexo.url(:original, false) %></span>
     </div>
     <% if current_user.admin? %>
     <div class="<%= @class %>">
       <span>
         <%= link_to 'Destroy', mat, method: :delete,data: { confirm: 'Are you sure?' } %>
       </span>
     </div>
     <% end %>
     <% end %>

   </div>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form' %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
    Disciplinas
  </h1>
   <ol class="breadcrumb">
     <li>
     <i class="glyphicon glyphicon-home"></i><a href="/"> Home</a>
     </li>
      <li class="active">
      <i class="glyphicon glyphicon-education"></i> Disciplinas
    </li>
  </ol>
</div>
</div>

<div class="col-lg-12" >
  <div class="panel panel-success">
    <div class="panel-heading">Minhas Disciplinas</div>
    <div class="panel body">
  <table class="table table-bordered table-hover table-striped">
    <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th colspan="4">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.codigo %></td>
        <td><%= discipline.nome %></td>
        <td><%= link_to 'Materiais',  '#', 'data-target' => "#myModal3_#{discipline.id}", 'data-toggle' => 'modal'  %></td>
        <div class="modal fade" id='<%= "myModal3_#{discipline.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Materiais</h4>
              </div>
              <div class="modal-body">
                <%= render 'showMateriais', discipline: discipline %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <% if !current_user.admin? %>
        <td><%= link_to 'Notas',  '#', 'data-target' => "#myModal2_#{discipline.id}", 'data-toggle' => 'modal'  %></td>
        <div class="modal fade" id='<%= "myModal2_#{discipline.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Notas</h4>
              </div>
              <div class="modal-body">
                <%= render 'showDetails', discipline: discipline %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <%end%>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit',  '#', 'data-target' => "#myModal_#{discipline.id}", 'data-toggle' => 'modal'  %></td>
        <div class="modal fade" id='<%= "myModal_#{discipline.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
              </div>
              <div class="modal-body">
                <%= render 'edit', discipline: discipline %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <td><%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
      <% end %>
    </tbody>
  </table>
    </div>
  </div>
</div>

<%if current_user.admin? %>

<%= link_to '',  '#', 'data-target' => "#myModal", 'data-toggle' => 'modal'  %>
<div class="modal fade" id='<%= "myModal" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', discipline: @discipline %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Button trigger modal -->
<div class="col-lg-12" >
<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
  Add Discipline
</button>
</div>

<% else %>

<%= link_to '',  '#', 'data-target' => "#myModal", 'data-toggle' => 'modal'  %>
<div class="modal fade" id='<%= "myModal" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Realiza Matricula</h4>
      </div>
      <% @variable = Discipline.new %>
      <div class="modal-body">
        <%= render 'matricula', discuser: @variable %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Button trigger modal -->
<div class="col-lg-12" >
<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
  Realizar Matricula
</button>
</div>
<% end %>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @discipline.nome %>
</p>

<p>
  <strong>Cargahoraria:</strong>
  <%= @discipline.cargahoraria %>
</p>

<%= link_to 'Back', disciplines_path %>