config/routes.rb
Rails.application.routes.draw do
  resources :absences
  resources :grades
  resources :activities
  resources :lessons
  resources :disciplines
  devise_for :users
  resources :courses
  resources :schools
  resources :discanexo

  post 'disciplines/:id' => 'disciplines#deleteAnexo'
  get 'update_users' => "grades#update_users", as: :update_users, defaults: { format: 'js' }

  get 'calendario' => 'activities#indexCalendar', as: :calendar
  
  get 'disciplines/:id/matricula' => 'disciplines#matricula', as: :matricula
  root 'activities#indexRoot'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :Discipline
    has_many :Grade, :dependent => :destroy

     def start_time
        self.data ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
    
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /activities
  # GET /activities.json
  def index
    if( current_user.admin? )
      @activities = Activity.where("Discipline_id IN (?)", Discipline.where( users_id: current_user.id).ids).order(data: :asc)
      @activity = Activity.new
    else
      @activities = Activity.where("Discipline_id in (?)", Discipline.joins(:Discuser).where("user_id = (?)", current_user.id).ids)
      @activity = Activity.new
    end
    end

  def indexCalendar
    if current_user.admin?
      @activities = Activity.where("data >= ? and Discipline_id IN (?)",
          Time.zone.now.to_date, Discipline.where( users_id: current_user.id).ids).
          order(data: :asc).reverse_order.limit(5).reverse
    else
      @activities = Activity
        .where("data >= ? and Discipline_id in (?)",
          Time.zone.now.to_date,
          Discipline.joins(:Discuser)
            .where("user_id = (?)", current_user.id).ids)
        .order(data: :asc).reverse_order.limit(5).reverse
    end
    render 'indexCalendar' 
  end

    # GET /activities
  # GET /activities.json
  def indexRoot
    if current_user.admin?
      @activities = Activity.where("data >= ? and Discipline_id IN (?)",
          Time.zone.now.to_date, Discipline.where( users_id: current_user.id).ids).
          order(data: :asc).reverse_order.limit(5).reverse
    else
      @activities = Activity
        .where("data >= ? and Discipline_id in (?)",
          Time.zone.now.to_date,
          Discipline.joins(:Discuser)
            .where("user_id = (?)", current_user.id).ids)
        .order(data: :asc).reverse_order.limit(5).reverse
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show

  end

  # GET /activities/new
  def new
    @activity = Activity.new

  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        flash[:success] = 'Atividade criada com sucesso.'
        format.html { redirect_to @activity }
        format.json { render :show, status: :created, location: @activity }
      else
        flash[:danger] = 'Erro ao criar atividade'
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        flash[:success] = 'Atividade alterada com sucesso.'
        format.html { redirect_to activities_url }
        format.json { render :show, status: :ok, location: @activity }
      else
        flash[:danger] = 'Erro ao alterar atividade.'
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      flash[:success] = 'Atividade excluida com sucesso.'
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find( params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:nome, :Discipline_id, :data)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(activity) do |f| %>
<% if activity.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

  <ul>
    <% activity.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :nome %><br>
  <%= f.text_field :nome, required: true %>
</div>
<div class="field">
  <%= f.label :Discipline %><br>
  <% @disciplines = Discipline.where( users_id: current_user.id)%>
  <%= f.select :Discipline_id, @disciplines.collect {|disc| [ disc.nome, disc.id ]}, required: true %>
</div>
<div class="field">
  <%= f.label :Data %><br>
  <%= f.date_field :data, {required: true }%>
</div>

<div class="modal-footer">
  <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
  <%= f.submit 'Save Changes', :class => 'btn btn-primary'  %>
</div>
<% end %>
  

app/views/activities/_show.html.erb
<p>
  <strong>Nome:</strong>
  <%= activity.nome %>
</p>

<p>
  <strong>Discipline:</strong>
  <%= activity.Discipline.try(:nome) %>
</p>


<p>
  <strong>Data:</strong>
  <%= activity.data %>
</p>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
    Atividades
  </h1>
   <ol class="breadcrumb">
     <li>
     <i class="glyphicon glyphicon-home"></i><a href="/"> Home</a>
     </li>
      <li class="active">
      <i class="glyphicon glyphicon-tasks"></i> Atividades
    </li>
  </ol>
</div>
</div>
<div class="col-lg-12" >
  <div class="panel panel-success">
    <div class="panel-heading">Minhas Atividades</div>
    <div class="panel body">
  <table class="table table-bordered table-hover table-striped">
    <thead>
      <tr>
        <th>Atividade</th>
        <th>Disciplina</th>
        <th>Data</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.nome %></td>
        <td><%= activity.Discipline.try(:nome) %></td>
        <td><%= activity.data.strftime("%d/%m/%Y")%></td>

        <td><%= link_to 'Show',  '#', 'data-target' => "#activity2_#{activity.id}", 'data-toggle' => 'modal'  %></td>
        <div class="modal fade" id='<%= "activity2_#{activity.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Informações</h4>
              </div>
              <div class="modal-body">
                <%= render 'show', activity: activity %>
              </div>
            </div><!-- /.modal-content -->

          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <% if current_user.admin? %>
        <td><%= link_to 'Edit',  '#', 'data-target' => "#activity_#{activity.id}", 'data-toggle' => 'modal'  %></td>
        <div class="modal fade" id='<%= "activity_#{activity.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Edit</h4>
              </div>
              <div class="modal-body">
                <%= render 'form', activity: activity %>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>
</div>
<% if current_user.admin? %>
<%= link_to '',  '#', 'data-target' => "#myModal", 'data-toggle' => 'modal'  %>
<div class="modal fade" id='<%= "myModal" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Nova Atividade</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', activity: @activity %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Button trigger modal -->
<div class="col-lg-12" >
<button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
  Nova Atividade
</button>
</div>
<%end%>

app/views/activities/indexCalendar.html.erb
<!-- Titulo e BreadCrump -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
    Calendário
  </h1>
   <ol class="breadcrumb">
     <li>
     <i class="glyphicon glyphicon-home"></i><a href="/"> Home</a>
     </li>
      <li class="active">
      <i class="glyphicon glyphicon-list-alt"></i> Calendário
    </li>
  </ol>
</div>
</div>
  <div class="col-lg-12">
<%= month_calendar events: @activities do |date, evt| %>
<%= date.strftime("%d/%m/%Y") %>

<% evt.each do |meeting| %>
<div>
<%= link_to meeting.nome, evt %><br>
</div>
<% end %>
<% end %>
</div>	

app/views/activities/indexRoot.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
    Próximas Atividades
  </h1>
   <ol class="breadcrumb">
    <li class="active">
      <i class="glyphicon glyphicon-home"></i> Home
    </li>
  </ol>
</div>
</div>
<div class="col-lg-12">
<div class="panel panel-success">
    <div class="panel-heading">Próximas Atividades</div>
    <div class="panel body">
    <table class="table table-bordered">
    <thead>
        <tr>
      <th>Atividade</th>
      <th>Disciplina</th>
      <th>Data</th>
      <th colspan="1">Ações</th>
        </tr>
    </thead>
    <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.nome %></td>
        <td><%= activity.Discipline.try(:nome) %></td>
        <td><%= activity.data.strftime("%d/%m/%Y")%></td>
        <td><%= link_to 'Show',  '#', 'data-target' => "#myModal2_#{activity.id}", 'data-toggle' => 'modal'  %></td>
      <div class="modal fade" id='<%= "myModal2_#{activity.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Informações</h4>
            </div>
            <div class="modal-body">
              <%= render 'show', activity: activity %>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </tr>
    <% end %>
    </tbody>
</table>
  </div>
  </div>
</div>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @activity.nome %>
</p>

<p>
  <strong>Discipline:</strong>
  <%= @activity.Discipline.try(:nome) %>
</p>


<p>
  <strong>Data:</strong>
  <%= @activity.data %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>