config/routes.rb
Rails.application.routes.draw do
  resources :absences
  resources :grades
  resources :activities
  resources :lessons
  resources :disciplines
  devise_for :users
  resources :courses
  resources :schools
  resources :discanexo

  post 'disciplines/:id' => 'disciplines#deleteAnexo'
  get 'update_users' => "grades#update_users", as: :update_users, defaults: { format: 'js' }

  get 'calendario' => 'activities#indexCalendar', as: :calendar
  
  get 'disciplines/:id/matricula' => 'disciplines#matricula', as: :matricula
  root 'activities#indexRoot'

end

app/models/absence.rb
class Absence < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :Discipline
    has_many :Grade, :dependent => :destroy

     def start_time
        self.data ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
    
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :School
end

app/models/discanexo.rb
class Discanexo < ActiveRecord::Base
	belongs_to :Discipline
	
	has_attached_file :anexo
  	do_not_validate_attachment_file_type :anexo
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :Course
  has_many :Activity, :dependent => :destroy
  has_many :Discuser, :dependent => :destroy
  has_many :Users, through: :Discuser
  belongs_to :Users
  has_many :discanexo, :dependent => :destroy

  validates_presence_of :nome, :cargahoraria

  def nomecompleto
  	"#{codigo} - #{nome}"
  end

end

app/models/discuser.rb
class Discuser < ActiveRecord::Base
      belongs_to :User
      belongs_to :Discipline
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :User
  belongs_to :Activity, :dependent => :destroy
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :Discipline
  has_attached_file :anexo
  do_not_validate_attachment_file_type :anexo
end

app/models/school.rb
class School < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :Discuser
  has_many :Discipline, through: :Discuser
  has_many :Discipline
  has_many :Grades
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/discanexo_helper.rb
module DiscanexoHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper

end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Vida Escolar • Colégio da Cidade</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<%= javascript_include_tag 'jquery', 'data-turbolinks-track' => true %>

	<%= javascript_include_tag 'bootstrap-datepicker.min', 'data-turbolinks-track' => true %>


	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= stylesheet_link_tag    'bootstrap-datepicker3.min', media: 'all', 'data-turbolinks-track' => true %>


	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	<%= stylesheet_link_tag    'sb-admin', media: 'all', 'data-turbolinks-track' => true %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>

</head>

<body>


	<div id="wrapper">

		<!-- Navigation -->
		<nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #2e7d32;" role="navigation">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
				</button>
				<a class="navbar-brand"  href="#">Vida Escolar</a>
			</div>
			<!-- Top Menu Items -->
			<ul class="nav navbar-right top-nav">
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
						<% if user_signed_in?  %>
						<%= current_user.email %>
						<% else  %>
						ACESSO
						<%end %>
						<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<%= render 'devise/menu/registration_items' %>
							<%= render 'devise/menu/login_items' %>
						</li>
					</ul>
					<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
					<div class="collapse navbar-collapse navbar-ex1-collapse" >
						<ul class="nav navbar-nav side-nav" style="background-color: #dff0d8;">
							<!--<% if user_signed_in?  %>
							<%= image_tag current_user.avatar.url(:thumb) %>
							<%end%>-->
							<li>
								<%= link_to  root_path do %>
								<i class="glyphicon glyphicon-home"> Home</i>
								<% end %>
							</li>
							<li>
								<%= link_to activities_path do %>
								<i class="glyphicon glyphicon-tasks"> Atividades</i>
								<% end %>
							</li>
							<li>

								<%= link_to disciplines_path do %>
								<i class="glyphicon glyphicon-education"> Disciplinas</i>
								<% end %>
							</li>
							<li>

								<%= link_to grades_path do %>
								<i class="glyphicon glyphicon-list-alt"> Notas</i>
								<% end %>
							</li>
							<li>

								<%= link_to calendar_path do %>
								<i class="glyphicon glyphicon-calendar"> Calendário</i>
								<% end %>
							</li>
							<li>

								<%= link_to root_path do %>
								<i class="glyphicon glyphicon-envelope"> Mensagens</i>
								<% end %>
							</li>
							<li>

								<%= link_to root_path, class: "" do %>
								<i class="glyphicon glyphicon-question-sign"> Ajuda</i>
								<% end %>
							</li>
						</ul>
					</div>
					<!-- /.navbar-collapse -->

				</nav>

				<div id="page-wrapper" >

					<!-- /.container-fluid -->


					<div>
						<% flash.each do |key, value| %>
						<div  class="alert alert-<%= key%> alert-dismissible">
							<%= value %></div>
							<% end %>
							<%= yield %>
						</div>

					</div>

				</div>

			</body>
			</html>

app/views/layouts/rapidfire.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Vida Escolar • Colégio da Cidade</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">


	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<%= stylesheet_link_tag    'sb-admin', media: 'all', 'data-turbolinks-track' => true %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>


</head>

<body>


<!-- Navigation -->
		<nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #2e7d32;" role="navigation">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
				</button>
				<a class="navbar-brand"  href="/..">Vida Escolar</a>
			</div>
			<!-- Top Menu Items -->
			<ul class="nav navbar-right top-nav">
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
						<% if user_signed_in?  %>
						<%= current_user.email %>
						<% else  %>
						ACESSO
						<%end %>
						<b class="caret"></b></a>
						<ul class="dropdown-menu">
								</li>
					</ul>

				</nav>

				<div id="page-wrapper">

					<!-- /.container-fluid -->

					<div>
						<%= yield %>
					</div>

				</div>
			</div>
</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>